apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: dqkqd/udagram-api-user:v1
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
