apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: dqkqd/udagram-api-feed:v1
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
