apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: udagram-api-feed
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: udagram-api-feed
