apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: udagram-frontend
spec:
  type: ClusterIP
  ports:
    - port: 8100
      targetPort: 80
  selector:
    app: udagram-frontend
