apiVersion: v1
kind: Service
metadata:
  name: publicreverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: udagram-reverseproxy
